### ISSUE TITLE
Any update ?

### ISSUE THREAD

**Issue by xmkevin** [aseemk/seadragon-ajax#8]
Hey, Is Seadragon-ajax still in developing ?

**Comment by aseemk** [comment]
I'm afraid not. While I'd love to develop it further, I'm currently pretty focused on my current full-time projects. Microsoft internally has developed Seadragon Ajax quite a bit further, but for internal use only.

But the reason this code was open-sourced was so that the community could do with it what they wanted. I could possibly offer advice or guidance to code and architectural questions. Good luck!

**Comment by xmkevin** [comment]
Thanks for your reply. I have built a project based on Seadragon Ajax 0.8.9, and I worry about the future.  I wonder does Microsoft have a plan to make it public later? Can you tell us a litter about the new features that has been developed internally ?

**Comment by aseemk** [comment]
I wouldn't worry about the future if the current state of the code meets your needs -- it's been open-sourced, so you won't lose it or anything like that.

I no longer work at Microsoft, so I can't say what their plans will be, but I wouldn't bet on them releasing anything publicly anytime soon.

Hope this helps!

**Comment by xmkevin** [comment]
Thanks for you kindly help.
